# Generated by Django 3.2 on 2021-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
